#pragma once

// This header is generated by CMake from config.h.in
#include "config.h"

// Version macros from config.h
#ifndef RECOVERYSUITE_VERSION_MAJOR
#define RECOVERYSUITE_VERSION_MAJOR 0
#endif

#ifndef RECOVERYSUITE_VERSION_MINOR
#define RECOVERYSUITE_VERSION_MINOR 0
#endif

#ifndef RECOVERYSUITE_VERSION_PATCH
#define RECOVERYSUITE_VERSION_PATCH 0
#endif